name: PowerShell Lint

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - "modules/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PowerShell/setup-powershell@v2
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      - name: Run Analyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./modules -Recurse -Severity Warning,Error -ReportSummary
